// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phone_Book;

#nullable disable

namespace Phone_Book.Migrations
{
    [DbContext(typeof(CallersContext))]
    [Migration("20250416080331_RequiredFields")]
    partial class RequiredFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Phone_Book.Caller", b =>
                {
                    b.Property<int>("CallerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CallerId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Callers");

                    b.HasData(
                        new
                        {
                            CallerId = 1,
                            Address = "123 Main St",
                            CategoryId = 1,
                            Email = "pasha@example.com",
                            Name = "Pasha",
                            Number = "(+38)-096-123-0001"
                        },
                        new
                        {
                            CallerId = 2,
                            Address = "456 Elm St",
                            CategoryId = 2,
                            Email = "olga@example.com",
                            Name = "Olga",
                            Number = "(+38)-068-987-0002"
                        },
                        new
                        {
                            CallerId = 3,
                            Address = "789 Oak St",
                            CategoryId = 3,
                            Email = "ivan@example.com",
                            Name = "Ivan",
                            Number = "(+38)-096-654-0003"
                        },
                        new
                        {
                            CallerId = 4,
                            Address = "101 Pine St",
                            CategoryId = 4,
                            Email = "sofia@example.com",
                            Name = "Sofia",
                            Number = "(+38)-068-321-0004"
                        },
                        new
                        {
                            CallerId = 5,
                            Address = "202 Maple St",
                            CategoryId = 1,
                            Email = "dmytro@example.com",
                            Name = "Dmytro",
                            Number = "(+38)-096-555-0005"
                        },
                        new
                        {
                            CallerId = 6,
                            Address = "303 Birch St",
                            CategoryId = 2,
                            Email = "kateryna@example.com",
                            Name = "Kateryna",
                            Number = "(+38)-068-789-0006"
                        },
                        new
                        {
                            CallerId = 7,
                            Address = "404 Cedar St",
                            CategoryId = 3,
                            Email = "andriy@example.com",
                            Name = "Andriy",
                            Number = "(+38)-096-345-0007"
                        },
                        new
                        {
                            CallerId = 8,
                            Address = "505 Walnut St",
                            CategoryId = 4,
                            Email = "natalia@example.com",
                            Name = "Natalia",
                            Number = "(+38)-068-234-0008"
                        },
                        new
                        {
                            CallerId = 9,
                            Address = "606 Chestnut St",
                            CategoryId = 1,
                            Email = "oleh@example.com",
                            Name = "Oleh",
                            Number = "(+38)-096-876-0009"
                        },
                        new
                        {
                            CallerId = 10,
                            Address = "707 Spruce St",
                            CategoryId = 2,
                            Email = "mariya@example.com",
                            Name = "Mariya",
                            Number = "(+38)-068-543-0010"
                        },
                        new
                        {
                            CallerId = 11,
                            Address = "808 Fir St",
                            CategoryId = 3,
                            Email = "serhiy@example.com",
                            Name = "Serhiy",
                            Number = "(+38)-096-432-0011"
                        },
                        new
                        {
                            CallerId = 12,
                            Address = "909 Willow St",
                            CategoryId = 4,
                            Email = "yulia@example.com",
                            Name = "Yulia",
                            Number = "(+38)-068-765-0012"
                        },
                        new
                        {
                            CallerId = 13,
                            Address = "1010 Poplar St",
                            CategoryId = 1,
                            Email = "volodymyr@example.com",
                            Name = "Volodymyr",
                            Number = "(+38)-096-678-0013"
                        },
                        new
                        {
                            CallerId = 14,
                            Address = "1111 Aspen St",
                            CategoryId = 2,
                            Email = "anastasia@example.com",
                            Name = "Anastasia",
                            Number = "(+38)-068-890-0014"
                        },
                        new
                        {
                            CallerId = 15,
                            Address = "1212 Redwood St",
                            CategoryId = 3,
                            Email = "bohdan@example.com",
                            Name = "Bohdan",
                            Number = "(+38)-096-210-0015"
                        },
                        new
                        {
                            CallerId = 16,
                            Address = "1313 Sequoia St",
                            CategoryId = 4,
                            Email = "viktoria@example.com",
                            Name = "Viktoria",
                            Number = "(+38)-068-432-0016"
                        },
                        new
                        {
                            CallerId = 17,
                            Address = "1414 Cypress St",
                            CategoryId = 1,
                            Email = "mykola@example.com",
                            Name = "Mykola",
                            Number = "(+38)-096-543-0017"
                        },
                        new
                        {
                            CallerId = 18,
                            Address = "1515 Magnolia St",
                            CategoryId = 2,
                            Email = "iryna@example.com",
                            Name = "Iryna",
                            Number = "(+38)-068-654-0018"
                        },
                        new
                        {
                            CallerId = 19,
                            Address = "1616 Dogwood St",
                            CategoryId = 3,
                            Email = "taras@example.com",
                            Name = "Taras",
                            Number = "(+38)-096-765-0019"
                        },
                        new
                        {
                            CallerId = 20,
                            Address = "1717 Hickory St",
                            CategoryId = 4,
                            Email = "liliya@example.com",
                            Name = "Liliya",
                            Number = "(+38)-068-876-0020"
                        },
                        new
                        {
                            CallerId = 21,
                            Address = "1818 Sycamore St",
                            CategoryId = 1,
                            Email = "petro@example.com",
                            Name = "Petro",
                            Number = "(+38)-096-987-0021"
                        },
                        new
                        {
                            CallerId = 22,
                            Address = "1919 Beech St",
                            CategoryId = 2,
                            Email = "oksana@example.com",
                            Name = "Oksana",
                            Number = "(+38)-068-109-0022"
                        },
                        new
                        {
                            CallerId = 23,
                            Address = "2020 Alder St",
                            CategoryId = 3,
                            Email = "hanna@example.com",
                            Name = "Hanna",
                            Number = "(+38)-096-218-0023"
                        },
                        new
                        {
                            CallerId = 24,
                            Address = "2121 Maple St",
                            CategoryId = 4,
                            Email = "ruslan@example.com",
                            Name = "Ruslan",
                            Number = "(+38)-068-327-0024"
                        },
                        new
                        {
                            CallerId = 25,
                            Address = "2222 Elm St",
                            CategoryId = 1,
                            Email = "ludmila@example.com",
                            Name = "Ludmila",
                            Number = "(+38)-096-436-0025"
                        },
                        new
                        {
                            CallerId = 26,
                            Address = "2323 Oak St",
                            CategoryId = 2,
                            Email = "roman@example.com",
                            Name = "Roman",
                            Number = "(+38)-068-545-0026"
                        },
                        new
                        {
                            CallerId = 27,
                            Address = "2424 Pine St",
                            CategoryId = 3,
                            Email = "vasyl@example.com",
                            Name = "Vasyl",
                            Number = "(+38)-096-654-0027"
                        },
                        new
                        {
                            CallerId = 28,
                            Address = "2525 Cedar St",
                            CategoryId = 4,
                            Email = "oleksii@example.com",
                            Name = "Oleksii",
                            Number = "(+38)-068-763-0028"
                        },
                        new
                        {
                            CallerId = 29,
                            Address = "2626 Walnut St",
                            CategoryId = 1,
                            Email = "alina@example.com",
                            Name = "Alina",
                            Number = "(+38)-096-872-0029"
                        },
                        new
                        {
                            CallerId = 30,
                            Address = "2727 Chestnut St",
                            CategoryId = 2,
                            Email = "denys@example.com",
                            Name = "Denys",
                            Number = "(+38)-068-981-0030"
                        });
                });

            modelBuilder.Entity("Phone_Book.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Work"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Friends"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Other"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "All"
                        });
                });

            modelBuilder.Entity("Phone_Book.Caller", b =>
                {
                    b.HasOne("Phone_Book.Category", "Category")
                        .WithMany("Callers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Phone_Book.Category", b =>
                {
                    b.Navigation("Callers");
                });
#pragma warning restore 612, 618
        }
    }
}
